name: sight
version: git
summary: Inspect files
description: sight let you inspect your local files.
confinement: devmode
base: core18
parts:
  test-httplab:
    plugin: go
    go-importpath: github.com/complexorganizations/sight
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  sight:
    command: bin/sight
