name: sight
version: git
base: core18
grade: stable
confinement: strict
summary: Inspect files
description: sight let you inspect your local files.
parts:
  sight:
    plugin: go
    go-importpath: github.com/complexorganizations/sight
    source: .
    source-type: git
apps:
  sight:
    command: bin/sight
